import { ThemeProvider } from '@/components/theme-provider'
import { Inter } from 'next/font/google'
import type { Metadata } from 'next'
import Link from 'next/link'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Pokemon Finder',
  description: 'Generated by create next app'
}
// Providers wrap around our app and give them access to data
// NextThemesProvider - Give our app access to light/ dark mode
//Providers are generally on the client side ("use client")
//Switch from the light mode to the dark mode <-- UI/ needs the client ti exist.

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en'>
      <body className={inter.className}>
        <ThemeProvider attribute='class' defaultTheme='dark'>
          <main className='flex min-h-screen flex-col items-center p-24'>
            <div className='z-10 max-w-5xl w-full items-center justify-between font-mono text-sm lg:flex'>
              <Link href='/'>
                <h2 className='text-2xl text-bold'>Pokemon Finder</h2>
              </Link>
            </div>
            {children}
          </main>
        </ThemeProvider>
      </body>
    </html>
  )
}
